CC=g++
CFLAGS=-I. -I./include -I./sysdeps -I./sysdeps/include
DEPS = libufdt.h  ufdt_overlay.h  ufdt_types.h

objects = main.o ufdt_convert.o  ufdt_node.o  ufdt_node_dict.o  ufdt_overlay.o libufdt_sysdeps_posix.o  libufdt_sysdeps_vendor.o

O_fdt : $(objects)
	cc -o O_fdt $(objects)



%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

.PHONY : clean
clean :
	rm edit $(objects)